### ISSUE TITLE
Database Filesystem generation

### ISSUE THREAD

**Issue by Askarhi** [lixmal/keepass4web#12]
Hello, I have follow your topic and create my server. with package installation

 It's works until master password request 
I don't found how create the database Filesystem at the first launch . I have check the config_local.yml locate in /usr/share/keepass4web/ 

db.kdbx is locate in /etc/keepass4web like config information in yml file  and I have grant to www-data for read and writ on this folder
I have imagine like standard keepass woftware that db will be create automatically, but something wrong and I don't found where or how create the db file

I have try to create a db with windows program and upload on my serveur (without success)
Thanks for your help

**Comment by Askarhi** [comment]
I have fix issue myself
when I have explore the log file after change to debug level
I have found this error 
Cannot load XML library to parse database: Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module)

so I have try to install module xml with this command cpan XML::XPath or perl -MCPAN -e 'install XML::Parser'

but during installation I have a new error
Expat.xs:12:10: fatal error: expat.h: No such file or directory
 #include <expat.h>
          ^~~~~~~~~
compilation terminated.
Makefile:319: recipe for target 'Expat.o' failed
make[1]: *** [Expat.o] Error 1

I have fix it with installation some package about 'expat'  
apt-get install libexpat1 libexpat1-dev libxml-parser-perl expat
and install again cpan XML::XPath with succes :)

and now I can open the db file (generate on windows client keepass 2.41

Thanks

**Comment by Askarhi** [comment]
Now 

I search how to add new entry in database (copied from windows keepass software)

i don't found any button for add entry or something like

I don't know how to create a new database with keepass4web (myabe it's not possible)

**Comment by lixmal** [comment]
@Askarhi: there's no possibility to create databases, edit or add entries yet.
It only reads existing files only.
