### ISSUE TITLE
Can't install from Ubuntu PPA due to missing installation candidate

### ISSUE THREAD

**Issue by marianheinsen** [lixmal/keepass4web#13]
Hi, I tried installing keepass4web from Ubuntu PPA as described in the Readme on Ubuntu 18.04. Everything works fine, except that it does not find the installation candidate for "libdancer2-session-cookie-perl":

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libdancer2-session-cookie-perl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libdancer2-session-cookie-perl' has no installation candidate
```

I did make sure to add the PPA beforehand with this command:

```
sudo add-apt-repository ppa:lixmal/keepass4web
sudo apt-get update
```

Why is it not found?

**Comment by lixmal** [comment]
Sorry about that, I forgot to push that package for 18.04.
Should work now after an `apt update`.

**Comment by marianheinsen** [comment]
Thanks, it is working now!
