### ISSUE TITLE
LDAP - Default password

### ISSUE THREAD

**Issue by Senatar** [lixmal/keepass4web#6]
Hi,
I am stuck at the first screen, looking for the default/admin password.
I use ldap module .

Could-you provide  this default password or tell how to get success at first authentication?

thx

**Comment by lixmal** [comment]
Hi,

are you using an ldap server?
There's no default password, you'll have to use user/password stored in the directory server.
To create a user you'll have to use whatever tools the server software provides or something like `ldapadd` from ldap-utils

**Comment by Senatar** [comment]
I thought keepass4web came with some embedded ldap server.
Well, I understand I just have to run my directory server and edit the config_local.yml.

Thx for the infos

**Comment by lixmal** [comment]
Sorry, I'll make it clear in the docs.
